name: ğŸµ Gitea
on:
  push:
    branches:
      - 'Year*-*'
jobs:
  commit:
    name: ğŸ«– Commit to Gitea
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
      - name: ğŸ“ Commit
        id: commit
        run: |
          git config --global user.name 'PunGrumpy'
          git config --global user.email ${{ secrets.EMAIL_GITEA }}
          git remote add gitea https://gitea.com/Mephisto/KMITL.git
          git push gitea HEAD:${{ github.ref }}
